Export to txt, usfm and pdf
texttree/v-cana pull request #266
Opened 2023-01-17 08:20 UTC by Valyukhov

1. Export chapters to txt and pdf
2. Export books to usfm and pdf

2023-01-17 08:52 UTC, foxprogs commented on schema.sql
> +        SELECT  jsonb_object_agg(num, text) FROM PUBLIC.chapters WHERE chapters.book_id = handle_compile_book.book_id INTO book;
два пробела

2023-01-17 08:53 UTC, foxprogs commented on schema.sql
> +        SELECT  jsonb_object_agg(num, text) FROM PUBLIC.verses WHERE project_id = OLD.project_id AND chapter_id = OLD.id INTO chapter;
тут тоже по два пробела

2023-01-17 08:58 UTC, foxprogs commented on schema.sql
> +      END IF;
мне кажется эти три строки можно убрать

2023-01-17 09:03 UTC, foxprogs commented on schema.sql
> +        SELECT  jsonb_object_agg(num, text) FROM PUBLIC.chapters WHERE chapters.book_id = handle_compile_book.book_id INTO book;
для compile book и compile chapter я бы добавил еще сортировку, чтобы нумерация глав или стихов была от меньшего к большему. Потому что потом при рендере у тебя просто reduce и сборка. Я просто заметил что на сервере не всегда нумерация генерируется последовательно.

2023-01-17 09:08 UTC, foxprogs commented on utils/helper.js
> +          }
а для чего вот этот стиль если у тебя внутри бади лежит всего один див?
Этот стиль нужен для того чтобы при печати каждая глава начиналась с нового листа. Надо исправить верстку и стиль.

2023-01-17 09:13 UTC, foxprogs commented on utils/helper.js
> +        : book?.code,
Вот это вот не понял. Если есть код книги то написать его с заглавной буквы а если нет то просто его вывести. Но его же нет?)

2023-01-17 09:22 UTC, foxprogs commented on components/Project/BookList.js
> +      const cl = t('Chapter')
Если казахи будут работать, то тебе надо чтобы была локализация виканы на казахский(цыганский, уйгурский и т.д.). Иначе тут русские названия будут. И так про все языки. Может стоит перенести в настройки проекта, чтобы там указали названия всех книг на их языке и слова "Глава" и может слово "Псалом", мы же говорим 1ый Псалом а не 1ая глава книги Псалмов

2023-01-17 09:26 UTC, foxprogs commented on components/Project/DownloadBlock.js
> +import { downloadPdf, downloadTxt } from 'utils/helper'
порядок импортов

2023-01-17 09:26 UTC, foxprogs commented on components/Project/DownloadBlock.js
> +    <div className="flex justify-center ">
пустой пробел

2023-01-17 09:33 UTC, foxprogs requested changes
добавил комментарии по коду

2023-01-17 15:22 UTC, foxprogs commented on utils/helper.js
> +        ? book?.code[0].toUpperCase() + book?.code.slice(1)
Если первая цифра то надо тогда второй символ с большой буквы 2Ti

2023-01-19 09:27 UTC, Valyukhov commented on components/Project/BookList.js
> +      const cl = t('Chapter')
@foxprogs На спринте высказали мнение, что можн сделать как в Tcore - при сохранении добавлять недостающие теги, которые уникальны для каждого языка, в частности полное название книги - toc1 и название главы - cl.
Единственное - я пока не знаю где это буду хранить, либо в стейте( и каждый раз придётся пользователю указывать это, что не гуд), либо создать в таблице books - новую колонку и для chapters.

2023-01-19 09:28 UTC, Valyukhov commented on components/Project/BookList.js
> +      const cl = t('Chapter')
в этом ПР я это оставлю пустым, а в следующем буду делать эту форму для заполнения и там буду думать как это сделать

2023-01-19 11:00 UTC, Valyukhov commented on schema.sql
> +        SELECT  jsonb_object_agg(num, text) FROM PUBLIC.chapters WHERE chapters.book_id = handle_compile_book.book_id INTO book;
@foxprogs исправил, но не уверен, что это работает, как я ни пытался сделать обратную группировку - не получилось, возможно, потому что обьект, а не массив

2023-01-19 11:43 UTC, foxprogs commented on components/Project/BookList.js
> +      const cl = t('Chapter')
ok, тогда отмечу выполненным.

2023-01-19 11:49 UTC, foxprogs commented on components/Project/BookList.js
> +      const cl = t('Chapter')
Я бы при создании книги просил указать длинное и короткое название книги и название главы. Книга по любому будет выгружаться. Второе - можно эти данные использовать и в интерфейсе чтобы писать сразу правильное название книги. В общем как по мне - очень много плюсов если названия укажут сразу. Ни с кого не убудет, это не так сложно

2023-01-19 11:50 UTC, foxprogs commented on components/Project/BookList.js
> +      const cl = t('Chapter')
для чаптерс я бы не делал новую колонку. Название главы на уровне всей книги же. По сути у нас есть всего три варианта, глава, псалом, история.

2023-01-19 11:50 UTC, foxprogs commented on components/Project/BookList.js
> +      const cl = t('Chapter')
@Valyukhov выше написал пару комментариев

2023-01-19 11:55 UTC, foxprogs commented on schema.sql
> +        SELECT jsonb_object_agg(num, text ORDER BY num ASC) FROM PUBLIC.verses WHERE project_id = OLD.project_id AND chapter_id = OLD.id INTO chapter;
@Valyukhov а почему у тебя сортировка не там написана? Должно быть
SELECT text FROM verses WHERE chapter=2 ORDER BY num ASC;

2023-01-19 11:56 UTC, foxprogs commented on schema.sql
> +        New.text=chapter;
лучше в одном стиле писать, не New а NEW

2023-01-19 12:05 UTC, foxprogs commented on schema.sql
> +      "type" project_type NOT NULL DEFAULT 'bible'::project_type,
ошибка синтаксиса, запятая в конце

2023-01-19 12:12 UTC, foxprogs commented on schema.sql
> +     ALTER TABLE chapters ALTER COLUMN "text" TYPE jsonb USING "text"::jsonb;
Для чего этот запрос? По идее у тебя весь этот файл удаляет таблицы и заново их создает. По этому можешь сразу тип правильный поставить в запросе, где ты создаешь таблицу. 
А если это скрипт для миграции, то лучше для него выделать отдельное место. По идее ты его будешь только один запускать на уже существующей таблице с данными
![изображение](https://user-images.githubusercontent.com/30548361/213439803-806c26d5-1805-4cdd-932d-b69974139c71.png)
Ну и если тут было что-то раньше в текстовом формате, то он будет ругаться так как он не может обычный текст конвертировать в jsonb

2023-01-19 12:19 UTC, Valyukhov commented on schema.sql
> +        SELECT jsonb_object_agg(num, text ORDER BY num ASC) FROM PUBLIC.verses WHERE project_id = OLD.project_id AND chapter_id = OLD.id INTO chapter;
@foxprogs ошибку выкидывало, что в аггрегатной функции всё по-другому, я поэтому так переписал

```
4.2.7. Агрегатные выражения

Агрегатное выражение представляет собой применение агрегатной функции к строкам, выбранным запросом. Агрегатная функция сводит множество входных значений к одному выходному, как например, сумма или среднее. Агрегатное выражение может записываться следующим образом:

агрегатная_функция (выражение [ , ... ] [ предложение_order_by ] ) [ FILTER ( WHERE условие_фильтра ) ]
агрегатная_функция (ALL выражение [ , ... ] [ предложение_order_by ] ) [ FILTER ( WHERE условие_фильтра ) ]
агрегатная_функция (DISTINCT выражение [ , ... ] [ предложение_order_by ] ) [ FILTER ( WHERE условие_фильтра ) ]
агрегатная_функция ( * ) [ FILTER ( WHERE условие_фильтра ) ]
агрегатная_функция ( [ выражение [ , ... ] ] ) WITHIN GROUP ( предложение_order_by ) [ FILTER ( WHERE условие_фильтра ) ]

Здесь агрегатная_функция — имя ранее определённой агрегатной функции (возможно, дополненное именем схемы), выражение — любое выражение значения, не содержащее в себе агрегатного выражения или вызова оконной функции. Необязательные предложения предложение_order_by и условие_фильтра описываются ниже.
```
тут пример `SELECT array_agg(a ORDER BY b DESC) FROM table;`

2023-01-19 12:22 UTC, Valyukhov commented on schema.sql
> +        SELECT jsonb_object_agg(num, text ORDER BY num ASC) FROM PUBLIC.verses WHERE project_id = OLD.project_id AND chapter_id = OLD.id INTO chapter;
вот ещё пример из документации
`SELECT xmlagg(x) FROM (SELECT x FROM test ORDER BY y DESC) AS tab;`
но у меня не завёлся
и вообще я хотел jsonb_object_agg_strict использовать, чтобы пропускать нулевые значения, но функции в сапабейз не было почему-то, может postgresql старый на локале

2023-01-19 12:24 UTC, Valyukhov commented on schema.sql
> +     ALTER TABLE chapters ALTER COLUMN "text" TYPE jsonb USING "text"::jsonb;
@foxprogs это атавизм какой-то, надо настроить postgresql песочницу, чтобы там кодить
спасибо, уберу

2023-01-19 14:10 UTC, Valyukhov commented on utils/helper.js
> +  </head>
да, стиль хорош, но с Писанием не нужен  - как мне кажется, лучше смотрится подряд главы, с ОБИ может и пригодится

2023-01-19 17:37 UTC, Valyukhov commented on schema.sql
> +        SELECT jsonb_object_agg(num, text ORDER BY num ASC) FROM PUBLIC.verses WHERE project_id = OLD.project_id AND chapter_id = OLD.id INTO chapter;
@foxprogs 
![изображение](https://user-images.githubusercontent.com/74174349/213519030-019cdc4d-087d-480b-a297-7fa76c98b919.png)

2023-01-19 17:38 UTC, Valyukhov commented on schema.sql
> +        SELECT jsonb_object_agg(num, text ORDER BY num ASC) FROM PUBLIC.verses WHERE project_id = OLD.project_id AND chapter_id = OLD.id INTO chapter;
как бы я не пытался изменить порядок - json почему-то по ключам порядок делает

2023-01-20 06:43 UTC, foxprogs approved these changes

2023-01-23 08:32 UTC, merged