Create updater commits
texttree/v-cana pull request #270
Opened 2023-01-26 06:55 UTC by Valyukhov

Create new page with settings

2023-01-26 06:58 UTC, Valyukhov commented
пока не обновляю базу девелоп, проверьте код, sql если всё ок - я тогда запущу этот скрипт и обновлю, не уверен по политикам RLS, что всё ровно

2023-01-26 07:02 UTC, foxprogs commented on pages/api/projects/[code]/index.js
> +            'id, title, code, type, method, languages(orig_name,code),dictionaries_alphabet' //убрать - проверить, где использовал
лучше написать TODO и потом уже текст, так как тот же vscode вроде как парсит такие комментарии и может тебе где-то отдельно показать все тудушки.

2023-01-26 07:04 UTC, foxprogs commented on components/CommitsList.js
> +import React, { useEffect, useMemo, useState } from 'react'
`React` же вроде как не надо импортировать

2023-01-26 07:07 UTC, Valyukhov commented on pages/api/projects/[code]/index.js
> +            'id, title, code, type, method, languages(orig_name,code),dictionaries_alphabet' //убрать - проверить, где использовал
@foxprogs ,да, я там вытягивал base manifest и resources, себе пометил,убрал, а коммент забыл, спсибо

2023-01-26 07:16 UTC, foxprogs commented on migrations.sql
> +    --TODO Надо сделать RLS для аутентифицированных пользователей для чтения и инсерта, но ошибка вылетает, нужно проверить ещё раз
я бы не делал чтение ни для кого. А записывать через сервисный ключ, ты же это только на стороне сервера делаешь? Не на клиенте?

2023-01-26 07:17 UTC, foxprogs commented on migrations.sql
> +CREATE TABLE PUBLIC.logs (
может выше поставить дату или версию. Потому что к примеру верхний код для миграции второй раз же не надо запускать

2023-01-26 07:18 UTC, foxprogs commented on migrations.sql
> +      PUBLIC.dictionaries disable ROW LEVEL security;
а почему отключен роу левел секьюрити?

2023-01-26 07:21 UTC, foxprogs commented on schema.sql
> +      WITH CHECK (authorize(auth.uid(), project_id) IN ('admin', 'coordinator'));
точно ли координатор может менять любое поле в таблице? Не приведет к каким-то косякам? Если тебе надо изменять только одно какое-то поле, и с валидацией - то правильнее функцию написать для этого.

2023-01-26 07:22 UTC, foxprogs commented on schema.sql
> +    UPDATE
тот же вопрос что и выше

2023-01-26 07:22 UTC, foxprogs commented on schema.sql
> +      WITH CHECK (authorize(auth.uid(), project_id) IN ('admin', 'coordinator'));
тот же вопрос и тут, почему разрешил менять все в таблице

2023-01-26 07:24 UTC, foxprogs commented on schema.sql
> +      WITH CHECK (authorize(auth.uid(), project_id) IN ('admin', 'coordinator'));
для чего это

2023-01-26 07:24 UTC, foxprogs commented on schema.sql
> +      PUBLIC.dictionaries disable ROW LEVEL security;
почему дикшенерис а не логс

2023-01-26 07:24 UTC, foxprogs commented on schema.sql
> +      PUBLIC.dictionaries disable ROW LEVEL security;
и почему дизейбл а не энейбл

2023-01-26 07:25 UTC, foxprogs commented on migrations.sql
> +      WITH CHECK (authorize(auth.uid(), project_id) IN ('admin', 'coordinator'));
почему добавил эти полиси

2023-01-26 07:32 UTC, foxprogs commented on components/ProjectSettings.js
> +import React, { useEffect, useState } from 'react'
`React` вроде не нужен

2023-01-26 07:34 UTC, Pavel064 commented on components/CommitsList.js
> +import { useMethod } from 'utils/hooks'
порядок импортов

2023-01-26 07:34 UTC, Pavel064 commented on components/ProjectEdit.js
> +        <div className="">
пустой className

2023-01-26 07:34 UTC, Pavel064 commented on components/ProjectSettings.js
> +      .then((result) => console.log(result))
здесь ещё нужно логирование?

2023-01-26 07:34 UTC, Pavel064 commented on components/ProjectSettings.js
> +      <h1 className="h2 mb-3">List of commits</h1>
здесь не нужно использовать перевод, да?

2023-01-26 07:34 UTC, Pavel064 commented on pages/api/projects/[code]/update_commits.js
> +                      `Project #${project_id} - in ${book.code} chapter ${key} have more verses - ${jsonfromGit[key]} than before - ${book.chapters[key]} `
в конце пробел

2023-01-26 07:36 UTC, foxprogs commented on components/ProjectSettings.js
> +      <h1 className="h2 mb-3">List of commits</h1>
надо перевод

2023-01-26 07:39 UTC, foxprogs commented on components/ProjectSettings.js
> +      .then((result) => console.log(result))
надо `console.log` убрать, может на что-то заменить

2023-01-26 07:41 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +    const { data, error } = await supabase.from('logs').insert({
используй здесь сервисный ключ

2023-01-26 07:41 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +export default async function languageProjectHandler(req, res) {
название надо поменять

2023-01-26 07:57 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +            .update({
меня немного смущает что ты тут изменяешь данные в базе. Это очень рано. Дальше по коду у тебя есть несколько мест где при обновлении может выскочить исключение. Если это случится то ты не сможешь откатить, потому что у тебя нигде нет того, что же было раньше тут, в этих колонках. Тебе надо либо в блоке catch вернуть обратно поля эти, либо я бы обновлял в самый последний момент. Если выскочит эксцепшн то ты хоть как-то по логам сможешь вычислить что ты там добавил. И даже без логов будет видно какие стихи или главы пустые.

2023-01-26 08:03 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +          res.status(200).json({ ...data })
а что тут в data. По коду вроде пустой объект

2023-01-26 08:04 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +          res.status(200).json({ ...data })
тут тоже вроде пустой объект

2023-01-26 08:08 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +          if (JSON.stringify(book.chapters) !== JSON.stringify(jsonfromGit)) {
а получится избавиться от такой вложенности? Тяжело читать код.
```js
if (JSON.stringify(book.chapters) !== JSON.stringify(jsonfromGit)) {
    return res.status(200).json({success: true});
}
```

что-то типа того

2023-01-26 08:39 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +                      .update([{ verses: jsonfromGit[key] }])
![изображение](https://user-images.githubusercontent.com/30548361/214791908-0424053f-ad20-44df-b380-73999e5fb5be.png)
можно сразу получить результат

2023-01-26 08:41 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +                          .single()
у тебя это лежит внутри цикла, то есть постоянно будешь выполнять этот код, надо вынести чтобы было меньше запросов

2023-01-26 08:45 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +                          })
![изображение](https://user-images.githubusercontent.com/30548361/214792901-23073735-cc17-44cf-b63e-67398d7aeaec.png)
что если сформировать массив и сделать множественную вставку

2023-01-26 08:46 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +      res.status(200).json({ ...data })
тут вроде тоже до сих пор пусто, непонятно что именно должно было возвращаться

2023-01-26 08:47 UTC, foxprogs requested changes
нужны исправления

2023-01-27 09:02 UTC, Pavel064 submitted a review, later dismissed

2023-01-27 09:20 UTC, foxprogs commented on components/ProjectSettings.js
> +      {isErrorCommit && <div className="mt-3">Одна из ссылок на коммит некоректна</div>}
перевод

2023-01-27 09:20 UTC, foxprogs commented on components/ProjectSettings.js
> +          'сохранить'
перевод

2023-01-27 09:49 UTC, foxprogs commented on pages/api/projects/[code]/update_commits.js
> +        if (newResources && project_id && baseResource) {
у тебя эта же проверка внутри `updateProject`

2023-01-27 10:03 UTC, foxprogs commented on schema.sql
> +    $$;
это не безопасная функция. 
1. Самая большая проблема что я могу вызвать ее на клиенте, передать айди моего проекта, тогда авторизация пройдет. А потом передать левый айди книги и пустой джейсон. И все, логов нет, все потеряется. Надо поставить в апдейт проверку на айди проекта.
2. Это уже меньшая проблема, просто этот код можно вызвать на прямую.по этому хочется быть уверенным что json с главами верный, или же сохранить прошлое значение. Но если первое исправить, и если уверен что код у тебя не вызовет этот метод криво, то можно не исправлять

2023-01-27 10:04 UTC, foxprogs commented on schema.sql
> +        INSERT INTO PUBLIC.chapters (num, verses, book_id, project_id) VALUES (num , verses, book_id, project_id);
стоит убедиться что эта книга принадлежит этому проекту

2023-01-27 10:06 UTC, foxprogs commented on schema.sql
> +  CREATE FUNCTION PUBLIC.insert_additional_chapter(book_id BIGINT, verses int4,project_id BIGINT,num int2) RETURNS BOOLEAN
пробел перед `project_id` и перед `num`

2023-01-27 10:07 UTC, foxprogs commented on schema.sql
> +        INSERT INTO PUBLIC.chapters (num, verses, book_id, project_id) VALUES (num , verses, book_id, project_id);
лишний пробел перед `verses`

2023-01-27 10:08 UTC, foxprogs commented on schema.sql
> +  CREATE FUNCTION PUBLIC.update_verses_in_chapters(book_id BIGINT, verses INTEGER, num int2,project_id BIGINT) RETURNS JSON
int2 в верхнем регистре, пробел перед project_id

2023-01-27 10:09 UTC, foxprogs commented on schema.sql
> +        UPDATE PUBLIC.chapters SET verses = update_verses_in_chapters.verses WHERE chapters.book_id = update_verses_in_chapters.book_id AND chapters.num = update_verses_in_chapters.num;
та же проблема, не хватает проверки что эта книга принадлежит проекту

2023-01-27 10:10 UTC, foxprogs commented on schema.sql
> +        SELECT JSON_build_object(  'id',id,'started_at',started_at) FROM PUBLIC.chapters WHERE chapters.book_id = update_verses_in_chapters.book_id AND chapters.num = update_verses_in_chapters.num IN
форматирование `('id', id, 'started_at', started_at)`

2023-01-27 10:11 UTC, foxprogs commented on schema.sql
> +        SELECT JSON_build_object(  'id',id,'started_at',started_at) FROM PUBLIC.chapters WHERE chapters.book_id = update_verses_in_chapters.book_id AND chapters.num = update_verses_in_chapters.num IN
а для чего конвертировать, он же вроде и так вернет json

2023-01-27 10:11 UTC, foxprogs commented on schema.sql
> +  CREATE FUNCTION PUBLIC.insert_additional_verses(start_verse int2, finish_verse int2, chapter_id BIGINT, project_id INTEGER) RETURNS BOOLEAN
в верхнем регистре надо `int2`, а то везде по разному написано

2023-01-27 10:18 UTC, foxprogs commented on schema.sql
> +            (i , chapter_id, step_id, project_id);
лишний пробел после `i`
вопрос, если стих такой уже есть, не сломается ничего? просто вернет ошибку и ты ее обработаешь и запишешь в логи?
тут в plpgsql тоже можно как-то try catch использовать чтобы не сломался код

2023-01-27 10:19 UTC, foxprogs commented on schema.sql
> +        UPDATE PUBLIC.projects SET resources = update_resources_in_projects.resources ,  base_manifest = update_resources_in_projects.base_manifest WHERE id= project_id;
форматирование, пробелы перед запятой, 2 пробела после, нет пробела перед знаком "равно"

2023-01-27 10:22 UTC, foxprogs commented on schema.sql
> +        UPDATE PUBLIC.projects SET resources = update_resources_in_projects.resources ,  base_manifest = update_resources_in_projects.base_manifest WHERE id= project_id;
я бы для подстраховки записал в логи предыдущее значение. У меня логика такая, если вдруг что-то случится, на сколько реально вообще будет восстановить то что тут было. К примеру когда там нумерация меняется, думаю это не так сложно. Но когда какие-то структурные объекты затираются, есть переживание что, вдруг что-то на клиенте изменится, придет корявый формат и все. На клиенте нет же тестов, правильные ли джейсоны формирутся.
Но это не ошибка, это просто моя заметка, как бы я сделал.

2023-01-27 10:23 UTC, foxprogs requested changes
нужны исправления

2023-01-27 11:28 UTC, Valyukhov commented on schema.sql
> +        SELECT JSON_build_object(  'id',id,'started_at',started_at) FROM PUBLIC.chapters WHERE chapters.book_id = update_verses_in_chapters.book_id AND chapters.num = update_verses_in_chapters.num IN
@foxprogs ,без этого возвращает строку, и элемент из первого столбца  в ретерене, в общем получилось так, пробовал в скобках и без скобок

2023-01-29 18:57 UTC, merged